# Generated by Django 3.1.3 on 2022-02-23 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(max_length=50)),
                ('isActive', models.BooleanField(null=True)),
                ('isDelete', models.BooleanField()),
                ('insertUser', models.CharField(default='system', max_length=50)),
                ('insertDate', models.DateField(blank=True, default=None, null=True)),
                ('updateUser', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('updateDate', models.DateField(blank=True, default=None, null=True)),
                ('project', models.CharField(default='1', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('isActive', models.BooleanField(null=True)),
                ('isDelete', models.BooleanField()),
                ('insertUser', models.CharField(default='system', max_length=50)),
                ('insertDate', models.DateField(blank=True, default=None, null=True)),
                ('updateUser', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('updateDate', models.DateField(blank=True, default=None, null=True)),
                ('project', models.CharField(default='1', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroupTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(null=True)),
                ('isDelete', models.BooleanField()),
                ('insertUser', models.CharField(default='system', max_length=50)),
                ('insertDate', models.DateField(blank=True, default=None, null=True)),
                ('updateUser', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('updateDate', models.DateField(blank=True, default=None, null=True)),
                ('project', models.CharField(default='1', max_length=100)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.grouptable')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.employeeuser')),
            ],
        ),
        migrations.CreateModel(
            name='MenuTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_string', models.CharField(max_length=100)),
                ('url_string', models.CharField(max_length=250)),
                ('group_permission_id', models.CharField(max_length=50)),
                ('has_child', models.BooleanField(null=True)),
                ('isActive', models.BooleanField(null=True)),
                ('isDelete', models.BooleanField()),
                ('insertUser', models.CharField(max_length=50)),
                ('insertDate', models.DateField(blank=True, null=True)),
                ('updateUser', models.CharField(blank=True, max_length=50, null=True)),
                ('updateDate', models.DateField(blank=True, null=True)),
                ('project', models.CharField(max_length=100)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.menutable')),
            ],
        ),
        migrations.CreateModel(
            name='MenuGroupTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(null=True)),
                ('isDelete', models.BooleanField()),
                ('insertUser', models.CharField(default='system', max_length=50)),
                ('insertDate', models.DateField(blank=True, default=None, null=True)),
                ('updateUser', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('updateDate', models.DateField(blank=True, default=None, null=True)),
                ('project', models.CharField(default='1', max_length=100)),
                ('menu_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.grouptable')),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.menutable')),
            ],
        ),
    ]
