# Generated by Django 3.1.3 on 2022-02-23 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accidents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concerne_vehicule', models.CharField(help_text="Numéro de la voiture qui a fait l'accident. ", max_length=50, verbose_name='Immatriculation')),
                ('assureur', models.CharField(blank=True, max_length=250, null=True)),
                ('date_accident', models.DateField(verbose_name="Date de l'accident")),
                ('lieu_accident', models.CharField(max_length=500)),
                ('causes', models.TextField(verbose_name="Quelles sont les causes de l'accident?")),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_contrat', models.CharField(blank=True, max_length=20, null=True)),
                ('statut_assurance', models.CharField(choices=[('Encours', 'Encours'), ('Suspendre', 'Suspendre')], default='Non', max_length=15)),
                ('nombre_de_mois', models.IntegerField()),
                ('sous_couvert', models.CharField(blank=True, max_length=200, null=True, verbose_name='S/C')),
                ('categorie', models.CharField(choices=[('Tourisme', 'Tourisme'), ('Transport', 'Transport')], default='Tourisme', max_length=50)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('remainingdays', models.IntegerField(default=0)),
                ('blocked_date', models.DateField(auto_now=True)),
                ('unblocked_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marque_Vehicule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_marque', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ('nom_marque',),
            },
        ),
        migrations.CreateModel(
            name='Model_Vehicule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_model', models.CharField(max_length=50, unique=True)),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance_auto.marque_vehicule')),
            ],
            options={
                'ordering': ('nom_model',),
            },
        ),
        migrations.CreateModel(
            name='ProprietaireVehicule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CIN', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('numero_permis', models.CharField(blank=True, max_length=15, null=True, verbose_name='Numéro de permis')),
                ('photo', models.ImageField(blank=True, upload_to='Proprietaire/%Y/%m/%d')),
                ('adresse', models.TextField(max_length=100)),
                ('telephone', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Reglement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_reglement', models.CharField(blank=True, max_length=10, null=True)),
                ('date_reglement', models.DateField(auto_now_add=True)),
                ('montant_a_regler', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_de_paiment', models.CharField(choices=[('Espece', 'Espece'), ('Cheque', 'Cheque'), ('Carte de crédit', 'Carte de crédit'), ('Carte de débit', 'Carte de débit'), ('A crédit', 'A crédit')], max_length=15)),
                ('regle', models.BooleanField(default=False)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance_auto.contrat')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Matricule')),
                ('conducteur', models.CharField(blank=True, max_length=200, null=True, verbose_name='Personne autorisée')),
                ('permis', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de permis')),
                ('carroserie', models.CharField(blank=True, max_length=50, null=True)),
                ('type_carburant', models.CharField(choices=[('Essence', 'Essence'), ('Diesel', 'Diesel')], max_length=15, verbose_name='Energie')),
                ('date_mise_en_circulation', models.DateField()),
                ('puissance', models.CharField(max_length=20)),
                ('poids_a_vide', models.CharField(blank=True, max_length=10)),
                ('poids_autorise', models.CharField(blank=True, max_length=10, null=True)),
                ('longueur', models.CharField(blank=True, max_length=15, null=True)),
                ('largeur', models.CharField(blank=True, max_length=15, null=True)),
                ('nb_place', models.IntegerField(null=True)),
                ('numero_carte_grise', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance_auto.model_vehicule')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance_auto.proprietairevehicule')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='TypeContrat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garantie', models.CharField(choices=[('Responsabilité civile', 'Responsabilité civile'), ('Incendie du véhicule', 'Incendie du véhicule'), ('Vol du véhicule', 'Vol du véhicule'), ('Brise de Glasses', 'Brise de Glasses'), ('Dommages Coalisions', 'Dommages Coalisions'), ('Défense et Recours', 'Défense et Recours')], max_length=50, verbose_name='Type de garantie')),
                ('duration', models.CharField(max_length=50, verbose_name='Durée (en nombre de jours)')),
                ('montant_du_contrat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reparations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garagiste', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=250)),
                ('vehicule_repare', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=5, verbose_name='Les réparations sont elles finies?')),
                ('commentaires', models.TextField()),
                ('id_accident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance_auto.accidents')),
            ],
        ),
        migrations.CreateModel(
            name='ReglementContrat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance_auto.contrat')),
                ('reglement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance_auto.reglement')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalReglement',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code_reglement', models.CharField(blank=True, max_length=10, null=True)),
                ('date_reglement', models.DateField(blank=True, editable=False)),
                ('montant_a_regler', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_de_paiment', models.CharField(choices=[('Espece', 'Espece'), ('Cheque', 'Cheque'), ('Carte de crédit', 'Carte de crédit'), ('Carte de débit', 'Carte de débit'), ('A crédit', 'A crédit')], max_length=15)),
                ('regle', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contrat', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assurance_auto.contrat')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical reglement',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalContrat',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero_de_contrat', models.CharField(blank=True, max_length=20, null=True)),
                ('statut_assurance', models.CharField(choices=[('Encours', 'Encours'), ('Suspendre', 'Suspendre')], default='Non', max_length=15)),
                ('nombre_de_mois', models.IntegerField()),
                ('sous_couvert', models.CharField(blank=True, max_length=200, null=True, verbose_name='S/C')),
                ('categorie', models.CharField(choices=[('Tourisme', 'Tourisme'), ('Transport', 'Transport')], default='Tourisme', max_length=50)),
                ('created', models.DateField(blank=True, editable=False)),
                ('modified', models.DateField(blank=True, editable=False)),
                ('active', models.BooleanField(default=True)),
                ('remainingdays', models.IntegerField(default=0)),
                ('blocked_date', models.DateField(blank=True, editable=False)),
                ('unblocked_date', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('type_contrat', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assurance_auto.typecontrat')),
                ('utilisateur', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assurance_auto.vehicule')),
            ],
            options={
                'verbose_name': 'historical contrat',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAccidents',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('concerne_vehicule', models.CharField(help_text="Numéro de la voiture qui a fait l'accident. ", max_length=50, verbose_name='Immatriculation')),
                ('assureur', models.CharField(blank=True, max_length=250, null=True)),
                ('date_accident', models.DateField(verbose_name="Date de l'accident")),
                ('lieu_accident', models.CharField(max_length=500)),
                ('causes', models.TextField(verbose_name="Quelles sont les causes de l'accident?")),
                ('created', models.DateField(blank=True, editable=False)),
                ('modified', models.DateField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('Vehicule', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assurance_auto.vehicule')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical accidents',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Depenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_depense', models.CharField(blank=True, max_length=10, null=True)),
                ('objet', models.CharField(max_length=200)),
                ('beneficiaire', models.CharField(max_length=500, verbose_name='Bénéficiaire')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_depense', models.DateField()),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContratHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance_auto.contrat')),
            ],
        ),
        migrations.AddField(
            model_name='contrat',
            name='type_contrat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assurance_auto.typecontrat'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrat',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance_auto.vehicule'),
        ),
        migrations.AddField(
            model_name='accidents',
            name='Vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance_auto.vehicule'),
        ),
    ]
