# Generated by Django 3.1.3 on 2022-02-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance_auto', '0002_auto_20220224_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='tca',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='TCA'),
        ),
        migrations.AddField(
            model_name='historicalcontrat',
            name='tca',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='TCA'),
        ),
    ]
