# Generated by Django 3.1.3 on 2022-02-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance_auto', '0003_auto_20220224_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='tca',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='TCA 4%'),
        ),
        migrations.AlterField(
            model_name='historicalcontrat',
            name='tca',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='TCA 4%'),
        ),
    ]
