# Generated by Django 3.1.3 on 2022-02-25 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assurance_auto', '0004_auto_20220224_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreglement',
            name='created',
            field=models.DateField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalreglement',
            name='modified',
            field=models.DateField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reglement',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reglement',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
    ]
