# Generated by Django 3.1.3 on 2022-02-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance_auto', '0005_auto_20220225_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='nombre_de_mois',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontrat',
            name='nombre_de_mois',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
