# Generated by Django 3.1.3 on 2022-02-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance_auto', '0006_auto_20220225_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='numero_de_contrat',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontrat',
            name='numero_de_contrat',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalreglement',
            name='code_reglement',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reglement',
            name='code_reglement',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
