# Generated by Django 3.1.3 on 2022-02-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance_auto', '0007_auto_20220228_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='numero_de_contrat',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
