# Generated by Django 3.1.3 on 2022-02-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance_auto', '0008_auto_20220228_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglement',
            name='code_reglement',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
