# Generated by Django 3.1.3 on 2022-03-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance_auto', '0011_auto_20220303_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrat',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='historicalcontrat',
            name='categorie',
        ),
        migrations.AddField(
            model_name='typecontrat',
            name='categorie',
            field=models.CharField(choices=[('Tourisme', 'Tourisme'), ('Transport', 'Transport')], default='Tourisme', max_length=50),
        ),
    ]
