# Generated by Django 3.1.3 on 2022-03-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance_auto', '0012_auto_20220311_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typecontrat',
            name='garantie',
            field=models.CharField(choices=[('Responsabilité civile', 'RC'), ('Incendie du véhicule', 'IV'), ('Vol du véhicule', 'VV'), ('Brise de Glasses', 'BG'), ('Dommages Coalisions', 'DC'), ('Défense et Recours', 'DR')], max_length=50, verbose_name='Type de garantie'),
        ),
    ]
