# Generated by Django 3.1.3 on 2022-03-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance_auto', '0013_auto_20220311_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreglement',
            name='mode_de_paiment',
            field=models.CharField(choices=[('Espece', 'Espece'), ('Cheque', 'Cheque'), ('Huri money', 'Huri money'), ('Holo', 'Holo'), ('Mvola', 'Mvola')], max_length=15),
        ),
        migrations.AlterField(
            model_name='reglement',
            name='mode_de_paiment',
            field=models.CharField(choices=[('Espece', 'Espece'), ('Cheque', 'Cheque'), ('Huri money', 'Huri money'), ('Holo', 'Holo'), ('Mvola', 'Mvola')], max_length=15),
        ),
    ]
