# Generated by Django 3.1.3 on 2022-03-08 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[(1, '5%'), (2, '10%'), (3, '15%'), (4, '20%'), (5, '25%'), (6, '30%'), (7, '35%'), (8, '40%'), (9, '45%'), (10, '50%'), (11, '55%'), (12, '60%'), (13, '65%'), (14, '70%'), (15, '75%'), (16, '80%'), (17, '85%'), (18, '90%'), (19, '95%'), (20, '100%')], max_length=5)),
                ('ID_Company', models.CharField(max_length=50, verbose_name='Régistre de commerce')),
                ('name_comapany', models.CharField(max_length=300, verbose_name='Nom de la Société')),
                ('adresse_company', models.TextField(verbose_name='Adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Consultations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medecin', models.CharField(blank=True, max_length=250, null=True)),
                ('date_consultation', models.DateField()),
                ('amount_to_pay', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Frais de consultation')),
                ('Ordonnace', models.ImageField(upload_to='Ordonnaces/%Y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Hospital', models.CharField(max_length=50, verbose_name='Régistre de commerce')),
                ('name_hospital', models.CharField(max_length=300, verbose_name='Hôpital/Pharmacie')),
                ('docteur', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('regle', models.BooleanField(default=True, verbose_name='Réglé')),
                ('Facture', models.ImageField(upload_to='Fact_Reglement/%Y/%m/%d')),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurCompany.consultations')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_empl', models.CharField(max_length=50)),
                ('CIN', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='Employés/%Y/%m/%d')),
                ('adresse', models.TextField(max_length=100)),
                ('telephone', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurCompany.companies')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='consultations',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurCompany.employees'),
        ),
        migrations.AddField(
            model_name='consultations',
            name='hopital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurCompany.hospitals'),
        ),
    ]
