# Generated by Django 3.1.3 on 2022-03-12 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assurCompany', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='date_naiss',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='nb_enfant',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employees',
            name='sit_matrimoniale',
            field=models.CharField(choices=[('marié(e)', 'marié(e)'), ('célibataire', 'célibataire'), ('divorcé(e)', 'divorcé(e)'), ('Veuf(ve)', 'Veuf(ve)')], default='marié(e)', max_length=20, verbose_name='Situation matrimoniale'),
            preserve_default=False,
        ),
    ]
